# Generated by Django 5.2.3 on 2025-07-02 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название товара')),
                ('price', models.FloatField(verbose_name='Цена')),
                ('discounted_price', models.FloatField(verbose_name='Цена со скидкой')),
                ('rating', models.CharField(max_length=50, verbose_name='Рейтинг')),
            ],
            options={
                'verbose_name': 'Название товара',
                'verbose_name_plural': 'Название товаров',
                'ordering': ['title'],
            },
        ),
    ]
