# Generated by Django 5.2.3 on 2025-07-04 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parser', '0002_alter_item_discounted_price_alter_item_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='discounted_price',
        ),
        migrations.RemoveField(
            model_name='item',
            name='price',
        ),
    ]
