# Generated by Django 5.2.3 on 2025-07-04 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser', '0004_item_discounted_price_item_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='currency',
            field=models.CharField(default=1, max_length=10, verbose_name='Валюта'),
            preserve_default=False,
        ),
    ]
