# Generated by Django 5.2.3 on 2025-07-05 11:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser', '0005_item_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='rating_count',
            field=models.PositiveIntegerField(blank=True, default=None, help_text='Сколько раз товар был оценён пользователями', null=True, verbose_name='Количество оценок'),
        ),
        migrations.AlterField(
            model_name='item',
            name='currency',
            field=models.CharField(help_text='Валюта, в которой указана цена (например, BYN, USD, EUR)', max_length=10, verbose_name='Валюта'),
        ),
        migrations.AlterField(
            model_name='item',
            name='discounted_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, help_text='Цена товара после применения всех скидок', max_digits=10, null=True, verbose_name='Цена со скидкой'),
        ),
        migrations.AlterField(
            model_name='item',
            name='price',
            field=models.DecimalField(decimal_places=2, help_text='Полная цена товара', max_digits=11, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='item',
            name='rating',
            field=models.FloatField(blank=True, default=None, help_text='Средняя оценка товара (от 0.0 до 5.0)', null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(5.0)], verbose_name='Рейтинг'),
        ),
        migrations.AlterField(
            model_name='item',
            name='title',
            field=models.CharField(help_text='Полное наименование товара (до 255 символов)', max_length=255, verbose_name='Название товара'),
        ),
    ]
