# Generated by Django 5.2.3 on 2025-07-05 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser', '0006_item_rating_count_alter_item_currency_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='rating_count',
            field=models.PositiveIntegerField(blank=True, default=0, help_text='Сколько раз товар был оценён пользователями', null=True, verbose_name='Количество оценок'),
        ),
    ]
